2022-08-17 18:50:25,384 INFO    Thread-184:121981 [wandb_setup.py:_flush():75] Loading settings from /home/mgatlin3/.config/wandb/settings
2022-08-17 18:50:25,384 INFO    Thread-184:121981 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-08-17 18:50:25,384 INFO    Thread-184:121981 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'sweep-FT', 'entity': 'mgatlin3', 'root_dir': '/home/mgatlin3/FT', 'run_id': 'nxnhb8q5', 'sweep_param_path': '/home/mgatlin3/FT/wandb/sweep-3epcegps/config-nxnhb8q5.yaml', 'sweep_id': '3epcegps'}
2022-08-17 18:50:25,384 INFO    Thread-184:121981 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'sweep.py', 'program': '/home/mgatlin3/FT/sweep.py'}
2022-08-17 18:50:25,384 INFO    Thread-184:121981 [wandb_init.py:_log_setup():437] Logging user logs to /home/mgatlin3/FT/wandb/run-20220817_185025-nxnhb8q5/logs/debug.log
2022-08-17 18:50:25,384 INFO    Thread-184:121981 [wandb_init.py:_log_setup():438] Logging internal logs to /home/mgatlin3/FT/wandb/run-20220817_185025-nxnhb8q5/logs/debug-internal.log
2022-08-17 18:50:25,384 INFO    Thread-184:121981 [wandb_init.py:init():471] calling init triggers
2022-08-17 18:50:25,384 INFO    Thread-184:121981 [wandb_init.py:init():474] wandb.init called with sweep_config: {'batch_size': 4, 'dropout_c': 0.1, 'dropout_ga': 0, 'epoch': 50, 'learning_rate': 0.0005, 'num_features_c1': 32, 'num_features_c2': 128, 'num_features_c3': 32, 'num_features_c4': 64}
config: {'batch_size': 4, 'epochs': 5, 'dropout_c': 0.3, 'dropout_ga': 0.1, 'num_features_c1': 64, 'num_features_c2': 64, 'num_features_c3': 128, 'num_features_c4': 64, 'learning_rate': 0.0003}
2022-08-17 18:50:25,384 INFO    Thread-184:121981 [wandb_init.py:init():524] starting backend
2022-08-17 18:50:25,385 INFO    Thread-184:121981 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-17 18:50:25,388 INFO    Thread-184:121981 [backend.py:ensure_launched():217] starting backend process...
2022-08-17 18:50:25,394 INFO    Thread-184:121981 [backend.py:ensure_launched():222] started backend process with pid: 122268
2022-08-17 18:50:25,395 INFO    Thread-184:121981 [wandb_init.py:init():533] backend started and connected
2022-08-17 18:50:25,402 INFO    Thread-184:121981 [wandb_run.py:_config_callback():1131] config_cb None None {'batch_size': 4, 'dropout_c': 0.1, 'dropout_ga': 0, 'epoch': 50, 'learning_rate': 0.0005, 'num_features_c1': 32, 'num_features_c2': 128, 'num_features_c3': 32, 'num_features_c4': 64}
2022-08-17 18:50:25,404 INFO    Thread-184:121981 [wandb_init.py:init():597] updated telemetry
2022-08-17 18:50:25,421 INFO    Thread-184:121981 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-08-17 18:50:26,141 INFO    Thread-184:121981 [wandb_run.py:_on_init():1923] communicating current version
2022-08-17 18:50:26,228 INFO    Thread-184:121981 [wandb_run.py:_on_init():1927] got version response upgrade_message: "wandb version 0.13.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-08-17 18:50:26,229 INFO    Thread-184:121981 [wandb_init.py:init():659] starting run threads in backend
2022-08-17 18:50:30,364 INFO    Thread-184:121981 [wandb_run.py:_console_start():1897] atexit reg
2022-08-17 18:50:30,364 INFO    Thread-184:121981 [wandb_run.py:_redirect():1770] redirect: SettingsConsole.REDIRECT
2022-08-17 18:50:30,364 INFO    Thread-184:121981 [wandb_run.py:_redirect():1775] Redirecting console.
2022-08-17 18:50:30,365 ERROR   Thread-184:121981 [wandb_run.py:_redirect():1834] Failed to redirect.
Traceback (most recent call last):
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1827, in _redirect
    out_redir.install()
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/mgatlin3/.conda/envs/poop/lib/python3.9/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-08-17 18:50:30,365 INFO    Thread-184:121981 [wandb_init.py:init():684] run started, returning control to user process
2022-08-17 18:50:30,365 INFO    Thread-184:121981 [wandb_config.py:__setitem__():150] config set architecture_name = CNN - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7ff33dff0220>>
2022-08-17 18:50:30,365 INFO    Thread-184:121981 [wandb_run.py:_config_callback():1131] config_cb architecture_name CNN None
2022-08-17 18:50:30,503 INFO    Thread-184:121981 [wandb_run.py:_finish():1685] finishing run mgatlin3/sweep-FT/nxnhb8q5
2022-08-17 18:50:30,504 INFO    Thread-184:121981 [wandb_run.py:_atexit_cleanup():1866] got exitcode: 1
2022-08-17 18:50:30,505 INFO    Thread-184:121981 [wandb_run.py:_restore():1838] restore
2022-08-17 18:50:30,509 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 777
  total_bytes: 777
}

2022-08-17 18:50:30,666 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 777
  total_bytes: 777
}

2022-08-17 18:50:31,155 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 777
  total_bytes: 10165
}

2022-08-17 18:50:31,257 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 777
  total_bytes: 10165
}

2022-08-17 18:50:31,358 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10165
  total_bytes: 10165
}

2022-08-17 18:50:31,459 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10165
  total_bytes: 10165
}

2022-08-17 18:50:31,561 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10165
  total_bytes: 10165
}

2022-08-17 18:50:31,662 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10165
  total_bytes: 10165
}

2022-08-17 18:50:31,763 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10165
  total_bytes: 10165
}

2022-08-17 18:50:31,980 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10165
  total_bytes: 10165
}

2022-08-17 18:50:32,188 INFO    Thread-184:121981 [wandb_run.py:_on_finish():1995] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10165
  total_bytes: 10165
}
local_info {
}

2022-08-17 18:50:33,689 INFO    Thread-184:121981 [wandb_run.py:_footer_history_summary_info():3102] rendering history
2022-08-17 18:50:33,689 INFO    Thread-184:121981 [wandb_run.py:_footer_history_summary_info():3134] rendering summary
2022-08-17 18:50:33,690 INFO    Thread-184:121981 [wandb_run.py:_footer_sync_info():3057] logging synced files
