2022-08-27 16:29:16.628485: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/apps/Module/GCC/9.2.0/lib64
2022-08-27 16:29:16.628526: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-08-27 16:29:16.628902: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Found 1552 images belonging to 4 classes.
Found 252 images belonging to 4 classes.
Found 315 images belonging to 4 classes.
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 478, 638, 128)     3584
 max_pooling2d (MaxPooling2D  (None, 239, 319, 128)    0
 )
 dropout (Dropout)           (None, 239, 319, 128)     0
 conv2d_1 (Conv2D)           (None, 237, 317, 16)      18448
 max_pooling2d_1 (MaxPooling  (None, 118, 158, 16)     0
 2D)
 dropout_1 (Dropout)         (None, 118, 158, 16)      0
 conv2d_2 (Conv2D)           (None, 116, 156, 32)      4640
 max_pooling2d_2 (MaxPooling  (None, 58, 78, 32)       0
 2D)
 dropout_2 (Dropout)         (None, 58, 78, 32)        0
 conv2d_3 (Conv2D)           (None, 56, 76, 32)        9248
 max_pooling2d_3 (MaxPooling  (None, 28, 38, 32)       0
 2D)
 dropout_3 (Dropout)         (None, 28, 38, 32)        0
 global_average_pooling2d (G  (None, 32)               0
 lobalAveragePooling2D)
 dropout_4 (Dropout)         (None, 32)                0
 dense (Dense)               (None, 4)                 132
=================================================================
Total params: 36,052
Trainable params: 36,052
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
































































































97/97 [==============================] - 404s 4s/step - loss: 1.3007 - accuracy: 0.3692 - val_loss: 1.2402 - val_accuracy: 0.3730 - _timestamp: 1661632561.0000 - _runtime: 410.0000
Epoch 2/100
































































































97/97 [==============================] - 403s 4s/step - loss: 1.1197 - accuracy: 0.5148 - val_loss: 1.1590 - val_accuracy: 0.5079 - _timestamp: 1661632964.0000 - _runtime: 813.0000
Epoch 3/100
































































































97/97 [==============================] - 402s 4s/step - loss: 1.0853 - accuracy: 0.5296 - val_loss: 1.0635 - val_accuracy: 0.6270 - _timestamp: 1661633366.0000 - _runtime: 1215.0000
Epoch 4/100
































































































97/97 [==============================] - 402s 4s/step - loss: 0.9941 - accuracy: 0.5896 - val_loss: 1.1336 - val_accuracy: 0.5635 - _timestamp: 1661633767.0000 - _runtime: 1616.0000
Epoch 5/100
































































































97/97 [==============================] - 401s 4s/step - loss: 0.9390 - accuracy: 0.6218 - val_loss: 0.8768 - val_accuracy: 0.7103 - _timestamp: 1661634169.0000 - _runtime: 2018.0000
Epoch 6/100
































































































97/97 [==============================] - 402s 4s/step - loss: 0.8674 - accuracy: 0.6559 - val_loss: 0.8848 - val_accuracy: 0.7024 - _timestamp: 1661634571.0000 - _runtime: 2420.0000
Epoch 7/100
































































































97/97 [==============================] - 402s 4s/step - loss: 0.8490 - accuracy: 0.6695 - val_loss: 0.9198 - val_accuracy: 0.8016 - _timestamp: 1661634972.0000 - _runtime: 2821.0000
Epoch 8/100
































































































97/97 [==============================] - 402s 4s/step - loss: 0.7672 - accuracy: 0.7159 - val_loss: 0.6564 - val_accuracy: 0.7619 - _timestamp: 1661635374.0000 - _runtime: 3223.0000
Epoch 9/100
































































































97/97 [==============================] - 401s 4s/step - loss: 0.7401 - accuracy: 0.7216 - val_loss: 0.7375 - val_accuracy: 0.7619 - _timestamp: 1661635775.0000 - _runtime: 3624.0000
Epoch 10/100
































































































97/97 [==============================] - 401s 4s/step - loss: 0.6824 - accuracy: 0.7571 - val_loss: 0.6593 - val_accuracy: 0.7698 - _timestamp: 1661636177.0000 - _runtime: 4026.0000
Epoch 11/100
































































































97/97 [==============================] - 402s 4s/step - loss: 0.6624 - accuracy: 0.7519 - val_loss: 0.5176 - val_accuracy: 0.8333 - _timestamp: 1661636578.0000 - _runtime: 4427.0000
Epoch 12/100
































































































97/97 [==============================] - 401s 4s/step - loss: 0.6770 - accuracy: 0.7539 - val_loss: 0.5656 - val_accuracy: 0.8333 - _timestamp: 1661636980.0000 - _runtime: 4829.0000
Epoch 13/100
































































































97/97 [==============================] - 401s 4s/step - loss: 0.6141 - accuracy: 0.8067 - val_loss: 0.4960 - val_accuracy: 0.8452 - _timestamp: 1661637381.0000 - _runtime: 5230.0000
Epoch 14/100
































































































97/97 [==============================] - 401s 4s/step - loss: 0.6015 - accuracy: 0.7970 - val_loss: 0.5720 - val_accuracy: 0.7976 - _timestamp: 1661637782.0000 - _runtime: 5631.0000
Epoch 15/100
































































































97/97 [==============================] - 402s 4s/step - loss: 0.6075 - accuracy: 0.7893 - val_loss: 0.5719 - val_accuracy: 0.7976 - _timestamp: 1661638184.0000 - _runtime: 6033.0000
Epoch 16/100
































































































97/97 [==============================] - 401s 4s/step - loss: 0.5878 - accuracy: 0.7906 - val_loss: 0.5633 - val_accuracy: 0.7897 - _timestamp: 1661638585.0000 - _runtime: 6434.0000
Epoch 17/100
































































































97/97 [==============================] - 402s 4s/step - loss: 0.5566 - accuracy: 0.8106 - val_loss: 0.4804 - val_accuracy: 0.8135 - _timestamp: 1661638987.0000 - _runtime: 6836.0000
Epoch 18/100
































































































97/97 [==============================] - 401s 4s/step - loss: 0.5493 - accuracy: 0.8099 - val_loss: 0.4449 - val_accuracy: 0.8571 - _timestamp: 1661639389.0000 - _runtime: 7238.0000
Epoch 19/100
































































































97/97 [==============================] - 402s 4s/step - loss: 0.5472 - accuracy: 0.8119 - val_loss: 0.4926 - val_accuracy: 0.8413 - _timestamp: 1661639791.0000 - _runtime: 7640.0000
Epoch 20/100
































































































97/97 [==============================] - 401s 4s/step - loss: 0.5304 - accuracy: 0.8119 - val_loss: 0.5360 - val_accuracy: 0.8651 - _timestamp: 1661640192.0000 - _runtime: 8041.0000
Epoch 21/100





















22/97 [=====>........................] - ETA: 5:00 - loss: 0.5153 - accuracy: 0.8182
2022-08-27 18:44:45.079458: W tensorflow/core/framework/op_kernel.cc:1733] UNKNOWN: FileNotFoundError: [Errno 2] No such file or directory: 'images/train/farts/farts_10min.mp3_430-440sec_spec0.png'
Traceback (most recent call last):
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1030, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/engine/data_adapter.py", line 831, in wrapped_generator
    for data in generator_fn():
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/engine/data_adapter.py", line 957, in generator_fn
    yield x[i]
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/preprocessing/image.py", line 110, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/preprocessing/image.py", line 337, in _get_batches_of_transformed_samples
    img = image_utils.load_img(
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/utils/image_utils.py", line 393, in load_img
    with open(path, 'rb') as f:

23/97 [======>.......................] - ETA: 4:56 - loss: 0.5111 - accuracy: 0.8179
Traceback (most recent call last):
  File "/home/mgatlin3/FT/2dCNN_peachy.py", line 101, in <module>
    history = model.fit(train_generator, validation_data=val_generator, epochs=wandb.config.epochs, batch_size=wandb.config.batch_size,
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/integration/keras/keras.py", line 163, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:
FileNotFoundError: [Errno 2] No such file or directory: 'images/train/farts/farts_10min.mp3_430-440sec_spec0.png'
Traceback (most recent call last):
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1030, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/engine/data_adapter.py", line 831, in wrapped_generator
    for data in generator_fn():
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/engine/data_adapter.py", line 957, in generator_fn
    yield x[i]
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/preprocessing/image.py", line 110, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/preprocessing/image.py", line 337, in _get_batches_of_transformed_samples
    img = image_utils.load_img(
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/keras/utils/image_utils.py", line 393, in load_img
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'images/train/farts/farts_10min.mp3_430-440sec_spec0.png'
	 [[{{node PyFunc}}]]

24/97 [======>.......................] - ETA: 4:52 - loss: 0.5147 - accuracy: 0.8203